server:
 port: 10010
spring:
 application:
  name: api-gateway
 cloud:
  gateway:
    #default-filters:
     #- AddResponseHeader=name, itcast
    routes:
    #路由id,可以随意写
     - id: user-service-route
    #代理服务地址
       uri: lb://user-service
    #路由断言 可以配置映射路径
       predicates:
         - Path=/api/user/**  
          #- Path=/**
       filters: # 添加请求路径的前缀
       #- PrefixPath=/user
         - StripPrefix=1
         - MyParam=name
       
                  
eureka:
 client:
  service-url:
   defaultZone: http://127.0.0.1:10086/eureka
 instance: 
    prefer-ip-address: true             
       