spring:
 application:
   name: consumer-demo
eureka:
 client:
  service-url:
   defaultZone: http://localhost:10086/eureka  
  registry-fetch-interval-seconds: 30
  
# 配置熔断策略： 
hystrix: 
 command: 
  default: 
   circuitBreaker: 
    errorThresholdPercentage: 50  
    sleepWindowInMilliseconds: 10000 
    requestVolumeThreshold: 10  
   execution: 
    isolation: 
     thread: 
      timeoutInMilliseconds: 5000
ribbon: 
 ReadTimeout: 2000 # 读取超时时长 
 ConnectTimeout: 1000 # 建立链接的超时时长  
 MaxAutoRetries: 0 # 当前服务器的重试次数
 MaxAutoRetriesNextServer: 0 # 重试多少次服务 
 OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试 
feign: 
 hystrix: 
  enabled: true # 开启Feign的熔断功能   
logging: 
  level: 
   cn.zvc: debug
      